import { useState } from 'react';
import axios from 'axios';
import toast from 'react-hot-toast';
import CodeMirror from '@uiw/react-codemirror';
import { sql } from '@codemirror/lang-sql';
import { Sparkles, Copy, Download, Play, AlertTriangle, ShieldCheck, CheckCircle2, Info, Bookmark } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";

export default function SqlGeneratorPage() {
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedQuery, setGeneratedQuery] = useState("");
  const [explanation, setExplanation] = useState("");
  const [operation, setOperation] = useState("");
  const [tables, setTables] = useState([]);
  const [estimatedRows, setEstimatedRows] = useState("");
  const [riskLevel, setRiskLevel] = useState("");
  const [optimization, setOptimization] = useState("");
  const [alternativeQuery, setAlternativeQuery] = useState("");

  // Save Modal State
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [saveTitle, setSaveTitle] = useState("");
  const [isSavingQuery, setIsSavingQuery] = useState(false);

  const handleGenerate = async () => {
    if (!prompt) return;
    setIsGenerating(true);

    try {
      const response = await axios.post("http://localhost:5000/api/query/generate", { prompt });
      const data = response.data.data;
      let mainQuery = data.sql || data.generatedSql || "";
      if (mainQuery && !mainQuery.includes("-- Optimized Query")) {
        mainQuery = `-- Optimized Query generated by AI\n${mainQuery}`;
      }
      setGeneratedQuery(mainQuery);
      setAlternativeQuery(data.alternativeSql || "");
      setExplanation(data.explanation || "");
      setOperation(data.operation || data.operationType || "");
      setTables(data.tables || []);
      setEstimatedRows(data.estimatedRows || "~");
      setRiskLevel(data.riskLevel || "Low");
      setOptimization(data.optimization || "No specific optimization suggestions.");
    } catch (error) {
      console.error("Failed to generate SQL", error);
      const backendError = error.response?.data?.error || error.message;
      setGeneratedQuery(`-- Error generating SQL:\n-- ${backendError}\n\n-- Please try again in a few moments.`);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopy = () => {
    if (generatedQuery) {
      navigator.clipboard.writeText(generatedQuery);
      // Could add a toast notification here in the future
    }
  };

  const handleDownload = () => {
    if (generatedQuery) {
      const blob = new Blob([generatedQuery], { type: 'text/sql' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'query.sql';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  const handleOpenSaveModal = () => {
    setSaveTitle(prompt.substring(0, 50));
    setShowSaveModal(true);
  };

  const handleSaveQuery = async () => {
    if (!saveTitle.trim()) return;
    setIsSavingQuery(true);
    try {
      await axios.post("http://localhost:5000/api/saved-queries", {
        title: saveTitle.trim(),
        generatedSql: generatedQuery
      });
      toast.success("Query saved successfully!");
      setShowSaveModal(false);
    } catch (e) {
      toast.error("Failed to save query");
    } finally {
      setIsSavingQuery(false);
    }
  };

  return (
    <div className="space-y-6 h-full flex flex-col animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div>
        <h2 className="text-3xl font-bold tracking-tight">SQL Generator</h2>
        <p className="text-muted-foreground mt-2">Describe what you want, and let our AI build the query.</p>
      </div>

      {/* Prompt Area */}
      <Card className="bg-card/50 backdrop-blur-sm border-primary/20 shadow-lg shadow-primary/5">
        <CardContent className="p-4 relative">
          <textarea
            className="w-full min-h-[120px] bg-transparent resize-none outline-none text-lg placeholder:text-muted-foreground/50 text-foreground"
            placeholder='e.g., "Show me the top 5 customers by revenue this year"'
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
          />
          <div className="absolute bottom-4 right-4 flex items-center space-x-2">
            <button
              onClick={handleGenerate}
              disabled={isGenerating || !prompt}
              className="bg-primary hover:bg-primary/90 text-primary-foreground px-6 py-2.5 rounded-full text-sm font-medium flex items-center transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-md shadow-primary/20 hover:shadow-primary/30 hover:-translate-y-0.5"
            >
              {isGenerating ? (
                <div className="w-4 h-4 mr-2 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
              ) : (
                <Sparkles className="w-4 h-4 mr-2" />
              )}
              {isGenerating ? "Generating..." : "Generate SQL"}
            </button>
          </div>
        </CardContent>
      </Card>

      {/* Results Area */}
      {generatedQuery && (
        <div className="flex-1 min-h-0 flex flex-col space-y-6 mt-6">
          <Tabs defaultValue="option1" className="w-full">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-4 gap-4">
              <TabsList className="bg-zinc-100 dark:bg-zinc-900 border border-border/50 h-auto p-1 self-start">
                <TabsTrigger value="option1" className="py-2 px-4 data-[state=active]:bg-white dark:data-[state=active]:bg-zinc-800 data-[state=active]:shadow-sm">Optimized Query</TabsTrigger>
                <TabsTrigger value="option2" className="py-2 px-4 data-[state=active]:bg-white dark:data-[state=active]:bg-zinc-800 data-[state=active]:shadow-sm">Alternative Query</TabsTrigger>
              </TabsList>
            </div>

            <TabsContent value="option1" className="mt-0 outline-none">
              <div className="grid lg:grid-cols-5 gap-6">

                {/* Main SQL Editor - Clean code block with integrated header */}
                <Card className="lg:col-span-3 border-border/50 overflow-hidden flex flex-col shadow-sm">
                  {/* Editor Header with Actions */}
                  <div className="flex items-center justify-between px-4 py-2.5 bg-zinc-100 dark:bg-zinc-950/80 border-b border-border/50">
                    <span className="text-xs font-mono font-medium text-muted-foreground flex items-center">
                      <Sparkles className="w-3.5 h-3.5 mr-1.5 text-primary" /> optimized-query.sql
                    </span>
                    <div className="flex items-center space-x-1">
                      <button
                        onClick={handleOpenSaveModal}
                        className="flex items-center text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-zinc-200 dark:hover:bg-zinc-800 px-2 py-1.5 rounded transition-colors"
                        title="Save Query"
                      >
                        <Bookmark className="w-3.5 h-3.5 mr-1.5" /> Save
                      </button>
                      <button
                        onClick={handleCopy}
                        className="flex items-center text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-zinc-200 dark:hover:bg-zinc-800 px-2 py-1.5 rounded transition-colors"
                        title="Copy"
                      >
                        <Copy className="w-3.5 h-3.5 mr-1.5" /> Copy
                      </button>
                      <button
                        onClick={handleDownload}
                        className="flex items-center text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-zinc-200 dark:hover:bg-zinc-800 px-2 py-1.5 rounded transition-colors"
                        title="Download"
                      >
                        <Download className="w-3.5 h-3.5 mr-1.5" /> Download
                      </button>
                    </div>
                  </div>

                  <div className="flex-1 bg-zinc-50 dark:bg-[#0d0d0f] relative group border-b border-border/50">
                    <div className="absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-primary to-purple-500 z-10" />
                    <div className="p-4 pt-4">
                      <CodeMirror
                        value={generatedQuery}
                        height="300px"
                        extensions={[sql()]}
                        theme="dark" // Keeping dark theme for CodeMirror as requested
                        className="text-[14px] font-mono"
                        basicSetup={{
                          lineNumbers: true,
                          foldGutter: false,
                          highlightActiveLine: false,
                        }}
                      />
                    </div>
                  </div>
                  <div className="p-4 bg-muted/30 flex justify-between items-center">
                    <Badge variant="outline" className="bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20 px-3 py-1.5 text-sm font-medium">
                      <ShieldCheck className="w-4 h-4 mr-2" /> Syntax Validated
                    </Badge>
                    <button className="bg-primary hover:bg-primary/90 text-primary-foreground px-6 py-2.5 rounded-md text-sm font-medium flex items-center transition-all shadow-md shadow-primary/20 hover:shadow-primary/30 hover:-translate-y-0.5">
                      <Play className="w-4 h-4 mr-2 fill-current" /> Execute Query
                    </button>
                  </div>
                </Card>

                {/* Info Cards Side Panel */}
                <div className="lg:col-span-2 space-y-4">
                  <Card className="border-border/50 shadow-sm">
                    <CardHeader className="pb-3 bg-muted/20">
                      <CardTitle className="text-sm font-semibold flex items-center text-foreground">
                        <Info className="w-4 h-4 mr-2 text-primary" /> Explanation
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="text-sm text-muted-foreground pt-4 leading-relaxed">
                      {explanation || "No explanation provided."}
                      {tables && tables.length > 0 && (
                        <div className="mt-3 pt-3 border-t border-border/50">
                          <span className="text-xs font-semibold uppercase text-muted-foreground mr-2">Tables:</span>
                          {tables.map(t => (
                            <span key={t} className="text-primary font-mono text-xs bg-primary/10 px-1.5 py-0.5 mr-1.5 rounded-md border border-primary/20">{t}</span>
                          ))}
                        </div>
                      )}
                    </CardContent>
                  </Card>

                  <Card className="border-border/50 shadow-sm">
                    <CardHeader className="pb-3 bg-muted/20">
                      <CardTitle className="text-sm font-semibold flex items-center text-foreground">
                        <AlertTriangle className="w-4 h-4 mr-2 text-amber-500" /> Impact Analysis
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4 pt-4">
                      <div className="flex justify-between items-center text-sm border-b border-border/50 pb-3">
                        <span className="text-muted-foreground font-medium">Operation</span>
                        <Badge variant="outline" className="bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20 font-mono tracking-wider">{operation || "UNKNOWN"}</Badge>
                      </div>
                      <div className="flex justify-between items-center text-sm border-b border-border/50 pb-3">
                        <span className="text-muted-foreground font-medium">Estimated Rows</span>
                        <span className="font-semibold text-foreground text-base">{estimatedRows}</span>
                      </div>
                      <div className="flex justify-between items-center text-sm">
                        <span className="text-muted-foreground font-medium">Risk Level</span>
                        <Badge variant="outline" className={riskLevel === 'High' || operation === 'DELETE' || operation === 'DROP' ? "bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/20 px-3" : "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20 px-3"}>
                          {riskLevel || (operation === 'DELETE' || operation === 'DROP' ? 'High' : 'Low')}
                        </Badge>
                      </div>
                    </CardContent>
                  </Card>

                  <Card className="border-border/50 shadow-sm">
                    <CardHeader className="pb-3 bg-muted/20">
                      <CardTitle className="text-sm font-semibold flex items-center text-foreground">
                        <CheckCircle2 className="w-4 h-4 mr-2 text-purple-500" /> Optimization
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="text-sm text-muted-foreground pt-4 leading-relaxed">
                      {optimization}
                    </CardContent>
                  </Card>
                </div>

              </div>
            </TabsContent>

            <TabsContent value="option2">
              {alternativeQuery ? (
                <Card className="border-border/50 overflow-hidden flex flex-col shadow-sm">
                  <div className="flex items-center justify-between px-4 py-2.5 bg-zinc-100 dark:bg-zinc-950/80 border-b border-border/50">
                    <span className="text-xs font-mono font-medium text-muted-foreground">alternative-query.sql</span>
                  </div>
                  <div className="flex-1 bg-zinc-50 dark:bg-[#0d0d0f] relative group">
                    <div className="absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-primary to-purple-500 z-10" />
                    <div className="p-4 pt-4">
                      <CodeMirror
                        value={alternativeQuery}
                        height="300px"
                        extensions={[sql()]}
                        theme="dark"
                        className="text-[14px] font-mono"
                        basicSetup={{
                          lineNumbers: true,
                          foldGutter: false,
                          highlightActiveLine: false,
                        }}
                      />
                    </div>
                  </div>
                </Card>
              ) : (
                <Card className="p-12 text-center text-muted-foreground border-dashed border-2">
                  No alternative query was provided for this request.
                </Card>
              )}
            </TabsContent>
          </Tabs>
        </div>
      )}

      {/* Custom Save Modal */}
      {showSaveModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-card border border-border w-full max-w-md rounded-xl shadow-2xl p-6 animate-in zoom-in-95 duration-200">
            <h3 className="text-xl font-bold text-foreground mb-2 flex items-center">
              <Bookmark className="w-5 h-5 mr-2 text-primary" /> Save Query
            </h3>
            <p className="text-sm text-muted-foreground mb-4">Give this query a recognizable name so you can find it later.</p>
            <input 
              type="text" 
              value={saveTitle} 
              onChange={e => setSaveTitle(e.target.value)}
              className="w-full bg-background border border-border rounded-md px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 mb-6 text-foreground shadow-sm"
              placeholder="e.g., Top 5 employees by salary"
              autoFocus
            />
            <div className="flex justify-end space-x-3">
              <button 
                onClick={() => setShowSaveModal(false)}
                className="px-4 py-2 text-sm font-medium text-muted-foreground hover:bg-muted rounded-md transition-colors"
              >
                Cancel
              </button>
              <button 
                onClick={handleSaveQuery}
                disabled={!saveTitle.trim() || isSavingQuery}
                className="px-6 py-2 bg-primary hover:bg-primary/90 text-primary-foreground text-sm font-medium rounded-md transition-colors disabled:opacity-50 shadow-md shadow-primary/20"
              >
                {isSavingQuery ? 'Saving...' : 'Save Query'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
